
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jMenuItem2.setEnabled(false);
        jMenuItem3.setEnabled(false);
        jMenuItem4.setEnabled(false);
        jMenuItem7.setEnabled(false);
        jMenu2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_seres = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        sp_ki = new javax.swing.JSpinner();
        tf_raza = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        tf_planeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jd_ver = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_seres = new javax.swing.JList<>();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        abrirarchivo = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_archivo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jd_seres.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Raza");
        jd_seres.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 50));
        jd_seres.getContentPane().add(sp_ki, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, -1));
        jd_seres.getContentPane().add(tf_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, -1));
        jd_seres.getContentPane().add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, -1));
        jd_seres.getContentPane().add(tf_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 230, -1));

        jButton1.setText("Crear ser");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_seres.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 140, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre del planeta");
        jd_seres.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edad Maxima");
        jd_seres.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KI");
        jd_seres.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Seres");
        jd_seres.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -20, 320, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universo7.png"))); // NOI18N
        jd_seres.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jd_ver.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_seres.setModel(new DefaultListModel()

        );
        jScrollPane1.setViewportView(jl_seres);

        jd_ver.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 310, 420));

        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });
        jd_ver.getContentPane().add(jb_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 170, 70));

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });
        jd_ver.getContentPane().add(jb_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 160, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maxresdefault.jpg"))); // NOI18N
        jd_ver.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 660));

        ta_archivo.setColumns(20);
        ta_archivo.setRows(5);
        jScrollPane2.setViewportView(ta_archivo);

        javax.swing.GroupLayout abrirarchivoLayout = new javax.swing.GroupLayout(abrirarchivo.getContentPane());
        abrirarchivo.getContentPane().setLayout(abrirarchivoLayout);
        abrirarchivoLayout.setHorizontalGroup(
            abrirarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abrirarchivoLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
        abrirarchivoLayout.setVerticalGroup(
            abrirarchivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abrirarchivoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\zeno-sama.jpg")); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Crear Universo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agregar seres");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Listar seres en JList");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("Cargar Universo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Ver Universo txt");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem4.setText("Salir del Universo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Guardar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Guardar en archivo de texto");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1189, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese nombre del universo");
        seleccionado = new Universo(nombre);

        JOptionPane.showMessageDialog(this, "Se creo el universo correctamente");
        JOptionPane.showMessageDialog(this, "Usted esta trabajando con el universo " + seleccionado.getNombre());
        jMenuItem2.setEnabled(true);
        jMenuItem1.setEnabled(false);
        jMenuItem4.setEnabled(true);
        jMenuItem7.setEnabled(false);
        jMenu2.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed

    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jd_seres.pack();
        jd_seres.setModal(true);
        jd_seres.setLocationRelativeTo(this);
        jd_seres.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        seleccionado.getSeres().add(new Ser(tf_raza.getText(), (Integer) sp_ki.getValue(), (Integer) sp_edad.getValue(), tf_planeta.getText()));
        DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
        modelo.removeAllElements();
        modelo.addElement(seleccionado.getSeres());
        tf_raza.setText("");
        sp_ki.setValue(0);
        sp_edad.setValue(0);
        tf_planeta.setText("");
        jMenuItem3.setEnabled(true);
        System.out.println(seleccionado.getSeres());

    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jd_ver.pack();
        jd_ver.setModal(true);
        jd_ver.setLocationRelativeTo(this);
        jd_ver.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        int pos = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la posicion del ser que desea modificar"));
        int op = Integer.parseInt(JOptionPane.showInputDialog(this, "1. modificar raza\n" + "2.modificar edad maxima\n" + "3.modificar ki\n" + "4.modificar planeta\n" + "Ingrese numero de opcion que desea modificar"));
        if (op == 1) {
            String n_raza = JOptionPane.showInputDialog("Ingrese nueva Raza");
            seleccionado.getSeres().get(pos).setRaza(n_raza);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
        if (op == 2) {
            int n_edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nueva edad maxima"));
            seleccionado.getSeres().get(pos).setAnios(n_edad);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
        if (op == 3) {
            int n_ki = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nuevo KI"));
            seleccionado.getSeres().get(pos).setKi(n_ki);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
        if (op == 4) {
            String n_planeta = JOptionPane.showInputDialog("Ingrese nuevo planeta");
            seleccionado.getSeres().get(pos).setRaza(n_planeta);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
    }//GEN-LAST:event_jb_modificarMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion del ser que desea elminar"));
        seleccionado.getSeres().remove(pos);
        DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
        modelo.removeAllElements();
        modelo.addElement(seleccionado.getSeres());
    }//GEN-LAST:event_jb_eliminarMouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        jMenuItem2.setEnabled(false);
        jMenuItem3.setEnabled(false);
        jMenu2.setEnabled(false);
        jMenuItem4.setEnabled(false);
        jMenuItem1.setEnabled(true);
        jMenuItem6.setEnabled(true);
        jMenuItem7.setEnabled(false);
       
        JOptionPane.showMessageDialog(this, "Ha salido del universo correctamente");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser jfc = new JFileChooser();
        int op = jfc.showSaveDialog(this);
        jfc.setName(seleccionado.getNombre() + ".txt");
        if (op == JFileChooser.APPROVE_OPTION) {
            seleccionado.setArchivo(jfc.getSelectedFile());
            try {
                seleccionado.escribirArchivo();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        JFileChooser jfc = new JFileChooser();
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        int op = jfc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            fichero = jfc.getSelectedFile();
            try {
                fr = new FileReader(fichero);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
            br = new BufferedReader(fr);
            String linea;
            try {
                while ((linea = br.readLine()) != null) {
                    ta_archivo.append(linea);
                    ta_archivo.append("\n");
                }
                JOptionPane.showMessageDialog(this, "universo cargado correctamente");
                jMenuItem2.setEnabled(false);
                jMenuItem3.setEnabled(false);
                jMenuItem4.setEnabled(true);
                jMenuItem1.setEnabled(false);
                jMenuItem6.setEnabled(false);
                jMenuItem7.setEnabled(true);
                jMenu2.setEnabled(false);
                

            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        abrirarchivo.pack();
        abrirarchivo.setModal(true);
        abrirarchivo.setLocationRelativeTo(this);
        abrirarchivo.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog abrirarchivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JDialog jd_seres;
    private javax.swing.JDialog jd_ver;
    private javax.swing.JList<String> jl_seres;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_ki;
    private javax.swing.JTextArea ta_archivo;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_raza;
    // End of variables declaration//GEN-END:variables
Universo seleccionado = null;
}
