
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jMenuItem2.setEnabled(false);
        jMenuItem3.setEnabled(false);
        jMenu2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_seres = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        sp_ki = new javax.swing.JSpinner();
        tf_raza = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        tf_planeta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jd_ver = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_seres = new javax.swing.JList<>();
        jb_modificar = new javax.swing.JButton();
        jb_eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jd_seres.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Raza");
        jd_seres.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 110, 50));
        jd_seres.getContentPane().add(sp_ki, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, -1));
        jd_seres.getContentPane().add(tf_raza, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, -1));
        jd_seres.getContentPane().add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 70, -1));
        jd_seres.getContentPane().add(tf_planeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 230, -1));

        jButton1.setText("Crear ser");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jd_seres.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, 140, 100));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre del planeta");
        jd_seres.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 250, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edad Maxima");
        jd_seres.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KI");
        jd_seres.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 60, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Seres");
        jd_seres.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, -20, 320, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/universo7.png"))); // NOI18N
        jd_seres.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jl_seres.setModel(new DefaultListModel()

        );
        jScrollPane1.setViewportView(jl_seres);

        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_eliminar.setText("Eliminar");
        jb_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_verLayout = new javax.swing.GroupLayout(jd_ver.getContentPane());
        jd_ver.getContentPane().setLayout(jd_verLayout);
        jd_verLayout.setHorizontalGroup(
            jd_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jd_verLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220)
                .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jd_verLayout.setVerticalGroup(
            jd_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_verLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jd_verLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\zeno-sama.jpg")); // NOI18N

        jMenu1.setText("Archivo");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Crear Universo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agregar seres");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Listar seres");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Guardar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String nombre = JOptionPane.showInputDialog("Ingrese nombre del universo");
        Universo u = new Universo(nombre);
        seleccionado = u;
        JOptionPane.showMessageDialog(this, "Se creo el universo correctamente");
        JOptionPane.showMessageDialog(this, "Usted esta trabajando con el universo " + seleccionado.getNombre());
        jMenuItem2.setEnabled(true);
        jMenuItem1.setEnabled(false);
        jMenu2.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        JFileChooser filechooser = new JFileChooser();
        int seleccion = filechooser.showSaveDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File dir = filechooser.getSelectedFile();
            boolean fuecreado = dir.mkdir();
            if (fuecreado) {
                JOptionPane.showMessageDialog(this, "Universo creado exitosamente");

            } else {
                JOptionPane.showMessageDialog(this, "El universo no fue creado exitosamente");
            }
        }
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jd_seres.pack();
        jd_seres.setModal(true);
        jd_seres.setLocationRelativeTo(this);
        jd_seres.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        seleccionado.getSeres().add(new Ser(tf_raza.getText(), (Integer) sp_ki.getValue(), (Integer) sp_edad.getValue(), tf_planeta.getText()));
        DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
        modelo.removeAllElements();
        modelo.addElement(seleccionado.getSeres());
        tf_raza.setText("");
        sp_ki.setValue(0);
        sp_edad.setValue(0);
        tf_planeta.setText("");
        jMenuItem3.setEnabled(true);
        System.out.println(seleccionado.getSeres());

    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        jd_ver.pack();
        jd_ver.setModal(true);
        jd_ver.setLocationRelativeTo(this);
        jd_ver.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
        int pos = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingrese la posicion del ser que desea modificar"));
        int op = Integer.parseInt(JOptionPane.showInputDialog(this, "1. modificar raza\n" + "2.modificar edad maxima\n" + "3.modificar ki\n" + "4.modificar planeta\n" + "Ingrese numero de opcion que desea modificar"));
        if (op == 1) {
            String n_raza = JOptionPane.showInputDialog("Ingrese nueva Raza");
            seleccionado.getSeres().get(pos).setRaza(n_raza);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
        if (op == 2) {
            int n_edad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nueva edad maxima"));
            seleccionado.getSeres().get(pos).setAnios(n_edad);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
        if (op == 3) {
            int n_ki = Integer.parseInt(JOptionPane.showInputDialog("Ingrese nuevo KI"));
            seleccionado.getSeres().get(pos).setKi(n_ki);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
        if (op == 4) {
            String n_planeta = JOptionPane.showInputDialog("Ingrese nuevo planeta");
            seleccionado.getSeres().get(pos).setRaza(n_planeta);
            DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
            modelo.removeAllElements();
            modelo.addElement(seleccionado.getSeres());
        }
    }//GEN-LAST:event_jb_modificarMouseClicked

    private void jb_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminarMouseClicked
        int pos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la posicion del ser que desea elminar"));
        seleccionado.getSeres().remove(pos);
        DefaultListModel modelo = (DefaultListModel) jl_seres.getModel();
        modelo.removeAllElements();
        modelo.addElement(seleccionado.getSeres());
    }//GEN-LAST:event_jb_eliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_eliminar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JDialog jd_seres;
    private javax.swing.JDialog jd_ver;
    private javax.swing.JList<String> jl_seres;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_ki;
    private javax.swing.JTextField tf_planeta;
    private javax.swing.JTextField tf_raza;
    // End of variables declaration//GEN-END:variables
Universo seleccionado = null;
}
